site_name: Golang-Guide
repo_url: https://github.com/ramitsurana/golang-guide/
site_author: Ramit Surana
pages:
- Home: index.md
- Content:
    - 'Developer': 'dev/env.md'
    - 'Web Framework': 'frameworks/web.md'
    - 'Logging': 'log/log.md'
    - 'Command Line': 'cmd/cli.md'
- About:
    - 'About': 'about/about.md'
    - 'License': 'about/LICENSE.md'
site_favicon: favicon.ico
theme: cosmo
remote_branch: gh-pages
